version: 1.0.{build}
branches:
  only:
  - master
skip_non_tags: true
image: WMF 5
clone_folder: c:\gopath\src\github.com\versent\saml2aws
environment:
  GOPATH: c:\gopath
  CHOCOLATEY_APIKEY:
    secure: mQ9vPmmwP1JqAdf45GK5Npl3iCfeRZPda08C2vQWiMxMfFj5WgNqCYEMZmDPxQRa
install:
- ps: >-
    write-output $env:GOPATH

    write-output $env:GOROOT

    $env:Path += ";`"$env:GOPATH\bin`";c:\go\bin;"

    go get github.com/Masterminds/glide

    write-output $env:PATH


    go version

    go env


    c:\gopath\bin\glide install 2> $null

    go build -o bin/saml2aws.exe -ldflags "-X main.Version=1.3.2" ./cmd/saml2aws

    mkdir ./choco/src

    copy-item ./bin/saml2aws.exe ./choco/src/saml2aws.exe

    cd choco

    choco pack saml2aws.nuspec
    
    cd ..

    choco apiKey -k $env:CHOCOLATEY_APIKEY -source https://chocolatey.org/

    choco push ./choco/saml2aws.1.3.2.nupkg
build_script:
- cmd: 7z a saml2aws.zip %APPVEYOR_BUILD_FOLDER%\bin\saml2aws.exe
artifacts:
- path: saml2aws.zip
- path: choco/saml2aws.1.3.2.nupkg
deploy:
- provider: GitHub
  release: saml2aws-$(appveyor_build_version)
  auth_token:
    secure: kxO8LOQfcXH15OdilgteFKRn4Y7vUQND84WaR2fgghgiwTTHPLgKV1j+6o/8Ggjx
  artifact: saml2aws.zip, choco/saml2aws.1.3.2.nupkg
  draft: false