version: 1.0.{build}
branches:
  only:
  - master
skip_non_tags: true
image: WMF 5
clone_folder: c:\gopath\src\github.com\versent\saml2aws
environment:
  GOPATH: c:\gopath
install:
- ps: >-
    write-output $env:GOPATH
    write-output $env:GOROOT
    $env:Path += ";`"$env:GOPATH\bin`";c:\go\bin;"
    go get github.com/Masterminds/glide

    write-output $env:PATH
    go version
    go env
    c:\gopath\bin\glide install 2> $null

build_script:
- cmd: >-
    go build -o bin/saml2aws.exe -ldflags "-X main.Version=1.3.2" ./cmd/saml2aws
    7z a saml2aws.zip %APPVEYOR_BUILD_FOLDER%\bin\saml2aws.exe
artifacts:
- path: saml2aws.zip
- path: choco/saml2aws.nupkg
deploy:
- provider: GitHub
  release: saml2aws-$(appveyor_build_version)
  auth_token:
    secure: kxO8LOQfcXH15OdilgteFKRn4Y7vUQND84WaR2fgghgiwTTHPLgKV1j+6o/8Ggjx
  artifact: saml2aws.zip, choco/saml2aws.nupkg
  draft: true